from odoo import models, fields, api, _


class SpaAppointment(models.Model):
    _inherit = 'spa.appointment'

    # ── Tap payment fields ────────────────────────────────────────────────────

    tap_charge_id = fields.Char(
        string='Tap Charge ID',
        copy=False,
        readonly=True,
        help='Charge ID returned by Tap Payments (chg_xxxxxxxxx).',
    )
    tap_payment_url = fields.Char(
        string='Tap Payment Link',
        copy=False,
        readonly=True,
        help='Hosted payment-page URL generated by Tap Payments.',
    )
    tap_payment_status = fields.Selection(
        selection=[
            ('INITIATED',  'Initiated'),
            ('CAPTURED',   'Captured / Paid'),
            ('VOID',       'Voided'),
            ('REFUNDED',   'Refunded'),
            ('DECLINED',   'Declined'),
            ('CANCELLED',  'Cancelled'),
            ('FAILED',     'Failed'),
        ],
        string='Tap Payment Status',
        copy=False,
        readonly=True,
        tracking=True,
    )
    tap_payment_generated_at = fields.Datetime(
        string='Link Generated At',
        copy=False,
        readonly=True,
    )

    # ── Computed helper ───────────────────────────────────────────────────────

    tap_is_paid = fields.Boolean(
        string='Paid via Tap',
        compute='_compute_tap_is_paid',
        store=True,
    )

    @api.depends('tap_payment_status')
    def _compute_tap_is_paid(self):
        for rec in self:
            rec.tap_is_paid = rec.tap_payment_status == 'CAPTURED'

    # ── Action: open Tap wizard ───────────────────────────────────────────────

    def action_tap_payment_link(self):
        """Open the Tap payment-link generation wizard."""
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _('Generate Tap Payment Link'),
            'res_model': 'tap.payment.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_appointment_id': self.id,
            },
        }

    # ── Called by webhook controller ─────────────────────────────────────────

    def _tap_update_payment_status(self, charge_id, status):
        """Update payment status from Tap webhook or redirect callback."""
        record = self.search([('tap_charge_id', '=', charge_id)], limit=1)
        if not record:
            return False
        record.write({'tap_payment_status': status})
        if status == 'CAPTURED':
            record.message_post(
                body=_('Payment confirmed by Tap Payments. Charge: %s') % charge_id,
                message_type='notification',
                subtype_xmlid='mail.mt_note',
            )
        return True
